# Generated by Django 3.1.2 on 2021-12-24 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductApp', '0001_initial'),
        ('BugApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Подмодуль')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=False, verbose_name='Статус удаления')),
                ('bugs', models.ManyToManyField(blank=True, to='BugApp.BugModel', verbose_name='Баги')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'db_table': 'Module',
            },
        ),
        migrations.CreateModel(
            name='SubSystemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Подсистема')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=False, verbose_name='Статус удаления')),
                ('modules', models.ManyToManyField(blank=True, to='ModuleApp.ModuleModel', verbose_name='Модули')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApp.productmodel', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Подсистема',
                'verbose_name_plural': 'Подсистемы',
                'db_table': 'SubSystem',
            },
        ),
    ]
