# Generated by Django 3.1.2 on 2021-12-24 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StatusApp', '0001_initial'),
        ('ModuleApp', '0002_auto_20211224_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulemodel',
            name='status_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StatusApp.statustypemodel', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='subsystemmodel',
            name='status_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StatusApp.statustypemodel', verbose_name='Статус'),
        ),
    ]
