# Generated by Django 3.1.2 on 2021-12-24 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductApp', '0001_initial'),
        ('FilesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('steps', models.TextField(verbose_name='Шаги воспроизведения')),
                ('actual_result', models.TextField(verbose_name='Фактический результат')),
                ('expected_result', models.TextField(verbose_name='Ожидаемый результат')),
                ('is_active', models.BooleanField(default=False, verbose_name='Статус удаления')),
                ('files', models.ManyToManyField(blank=True, to='FilesApp.FileModel', verbose_name='Файлы')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApp.productmodel', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Баг',
                'verbose_name_plural': 'Баги',
                'db_table': 'Bug',
            },
        ),
    ]
