# Generated by Django 3.1.2 on 2021-12-24 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StatusApp', '0001_initial'),
        ('BugApp', '0002_auto_20211224_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugmodel',
            name='priority_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StatusApp.prioritytypemodel', verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='bugmodel',
            name='problem_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StatusApp.problemtypemodel', verbose_name='Проблема'),
        ),
    ]
