# Generated by Django 3.1.2 on 2021-12-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Ключ')),
            ],
            options={
                'verbose_name': 'Тип приоритета',
                'verbose_name_plural': 'Типы приоритета',
                'db_table': 'PriorityType',
            },
        ),
        migrations.CreateModel(
            name='ProblemTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Ключ')),
            ],
            options={
                'verbose_name': 'Тип проблемы',
                'verbose_name_plural': 'Типы проблем',
                'db_table': 'ProblemType',
            },
        ),
        migrations.CreateModel(
            name='StatusTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Ключ')),
            ],
            options={
                'verbose_name': 'Тип статуса',
                'verbose_name_plural': 'Типы статусов',
                'db_table': 'StatusType',
            },
        ),
    ]
